main: com.luacraft.LuaCraft
version: 2.1.0
softdepend:
 - Vault
name: LuaCraft
author: BorpBorp
api-version: 1.21
commands:
  lua:
    description: A basic lua trigger command
    usage: /lua
    permission: lua.command
    permission-message: "You don't have permission to use this command"

permissions:
  lua.command:
    description: Allows use of /lua
    default: op